version: '3.3'

services:
  nginx:
    container_name: nginx
    image: nginx:1.23
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/configs:/etc/nginx/conf.d:ro
      - type: bind
        source: ./static
        target: /app/static
    depends_on:
      - app
    ports:
      - "80:8000"

  app:
    container_name: django
    build:  .
    command:  bash -c "python manage.py migrate && python manage.py collectstatic --no-input && python manage.py runserver 0.0.0.0:8000"
    expose:
      - "8000"
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - type: bind
        source: ./static
        target: /app/static

  postgres:
    image: postgres:13.3
    container_name: storage
    env_file:
      - .env
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
